version: '2'

services:

  session:
    image: redis
    restart: always
    volumes:
      - /vesta/redis:/data
    networks:
      - network

  database:
    image: mysql
    restart: always
    ports:
      - '3316:3306'
    volumes:
      - /vesta/mysql:/var/lib/mysql
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: '__DATABASE_PASSWORD__'
      MYSQL_DATABASE: vesta

  api:
    image: vesta/pm2
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
      - /vesta/upload:/upload
      - /vesta/log:/log
      - /vesta/ssl:/ssl
    networks:
      - network
    working_dir: /app
    command: pm2 start app.js --no-daemon
    environment:
      NODE_ENV: production
      LOG_LEVEL: 2
      PORT: 3000
      SDB_PROTOCOL: redis
      SDB_HOST: session
      SDB_PORT: 6379
      ADB_PROTOCOL: mysql
      ADB_HOST: database
      ADB_PORT: 3306
      ADB_USERNAME: root
      ADB_PASSWORD: '__DATABASE_PASSWORD__'
      ADB_NAME: vesta
      SALT: '__SALT__'
      SECRET_KEY: '__SECRET_KEY__'
    depends_on:
      - session
      - database

networks:
  network:
